version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: viniciof1211/green-carrot-exec-flow
    deploy:
      replicas: 15
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4050:3000"
    networks:
      - webnet
networks:
  webnet: