version: '2'
networks:
    clustnet:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/28
                  gateway: 10.0.0.1
services:
    config01:
        image: mongo
        command: 'mongod --port 27017 --configsvr --replSet configserver --dbpath /data/configdb'
        ports: 
            - '27017:27017'
        networks:
            clustnet:
                ipv4_address: 10.0.0.2
        volumes:
            - './scripts:/scripts'
    config02:
        image: mongo
        command: 'mongod --port 27018 --configsvr --replSet configserver --dbpath /data/configdb'
        ports:
            - '27018:27018'
        networks:
            clustnet:
                ipv4_address: 10.0.0.3
        volumes:
            - './scripts:/scripts'
    sj01:
        image: mongo
        command: 'mongod --port 27019 --shardsvr --replSet repsanjose --dbpath /data/db'
        ports:
            - '27019:27019'
        networks:
            clustnet:
                ipv4_address: 10.0.0.4
        volumes:
            - './scripts:/scripts'
    sj02:
        image: mongo
        command: 'mongod --port 27020 --shardsvr --replSet repsanjose --dbpath /data/db'
        ports:
            - '27020:27020'
        networks:
            clustnet:
                ipv4_address: 10.0.0.5
        volumes:
            - './scripts:/scripts'
    ca01:
        image: mongo
        command: 'mongod --port 27021 --shardsvr --replSet repcartago  --dbpath /data/db'
        ports:
            - '27021:27021'
        networks:
            clustnet:
                ipv4_address: 10.0.0.6
        volumes:
            - './scripts:/scripts'
    ca02:
        image: mongo
        command: 'mongod --port 27022 --shardsvr --replSet repcartago  --dbpath /data/db'
        ports:
            - '27022:27022'
        networks:
            clustnet:
                ipv4_address: 10.0.0.7
        volumes:
            - './scripts:/scripts'
    al01:
        image: mongo
        command: 'mongod --port 27023 --shardsvr --replSet repalajuela  --dbpath /data/db'
        ports:
            - '27023:27023'
        networks:
            clustnet:
                ipv4_address: 10.0.0.8
        volumes:
            - './scripts:/scripts'
    al02:
        image: mongo
        command: 'mongod --port 27024 --shardsvr --replSet repalajuela  --dbpath /data/db'
        ports:
            - '27024:27024'
        networks:
            clustnet:
                ipv4_address: 10.0.0.9
        volumes:
            - './scripts:/scripts'
    arb01sj:
        image: mongo
        command: 'mongod --port 27025 --replSet repsanjose  --dbpath /data/db'
        ports:
            - '27025:27025'
        networks:
            clustnet:
                ipv4_address: 10.0.0.10
        volumes:
            - './scripts:/scripts'
    arb01ca:
        image: mongo
        command: 'mongod --port 27026  --replSet repcartago  --dbpath /data/db'
        ports:
            - '27026:27026'
        networks:
            clustnet:
                ipv4_address: 10.0.0.11
        volumes:
            - './scripts:/scripts'
    arb01al:
        image: mongo
        command: 'mongod --port 27027  --replSet repalajuela  --dbpath /data/db'
        ports:
            - '27027:27027'
        networks:
            clustnet:
                ipv4_address: 10.0.0.12
        volumes:
            - './scripts:/scripts'
    router01:
        image: mongo
        command: 'mongos --port 27028 --bind_ip 10.0.0.13 --configdb configserver/config01:27017,config02:27018'
        networks:
            clustnet:
                ipv4_address: 10.0.0.13
        ports:
            - '27028:27028'
        volumes:
            - './scripts:/scripts'
        depends_on:
            - config01
            - config02
            - sj01
            - sj02
            - ca01
            - ca02
            - al01
            - al02
    router02:
        image: mongo
        command: 'mongos --port 27029 --bind_ip 10.0.0.14 --configdb configserver/config01:27017,config02:27018'
        networks:
            clustnet:
                ipv4_address: 10.0.0.14
        ports:
            - '27029:27029'
        volumes:
            - './scripts:/scripts'
        depends_on:
            - config01
            - config02
            - sj01
            - sj02
            - ca01
            - ca02
            - al01
            - al02
